### ISSUE TITLE
Can not install gems

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community-attic/inception-server#14]
```
$ gem install bundler
Fetching: bundler-1.3.5.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /usr/local/rvm/gems/ruby-1.9.3-p429 directory.
```

**Comment by mdub** [comment]
Ah! I've just got up to the part in the bosh-boostrap README that tells me to:

```
$ inception deploy
$ inception ssh
> gem install bosh-bootstrap
```

and hit this problem; "gem install bosh-boostrap" as the "ubuntu" user fails.

It looks like the problem is that RVM is installed system-wide, and user "ubuntu" doesn't have permissions to write into $GEM_HOME.

I tried (manually) adding "ubuntu" to the "rvm" group, which has write permission to $GEM_HOME.  Unfortunately not to subdirectories, though:

```
ubuntu:~$ ls -la $GEM_HOME
total 28
drwxrwsr-x  7 root rvm 4096 Jun 13 06:49 .
drwxrwsr-x  5 root rvm 4096 Jun 13 06:24 ..
drwxr-sr-x  2 root rvm 4096 Jun 13 06:33 bin
drwxr-sr-x  2 root rvm 4096 Jun 13 06:33 cache
drwxr-sr-x  2 root rvm 4096 Jun 13 06:29 doc
drwxr-sr-x 59 root rvm 4096 Jun 13 06:33 gems
drwxrwsr-x  2 root rvm 4096 Jun 13 06:33 specifications
```

I suspect that that's a bug in the rvm cookbook, since the "rvm" group appears to exist to allow selected users permission to modify the system-level RVM install.  So, one option might be to fix that "bug", and arrange for "ubuntu" to be in the "rvm" group.

Alternatively, perhaps inception-server could install RVM in one of it's documented "mixed modes", so that gems end up in $HOME (see https://rvm.io/rvm/install).

@drnic, any thoughts?

**Comment by mdub** [comment]
Note that you can bypass the file-permission problems by creating a Gemfile, and running "bundle install". This is because Bundler automatically uses "sudo" when it can't write to $GEM_HOME; the gems end up owned by root :-)

**Comment by yudai** [comment]
Hi Nic and Mike,
Any progress or plan on this issue?
I manually replaced RVM with rbenv on my inception server, however It takes much time to install and I don't want to repeat that.
@mdub's chruby PR looks good to me.

**Comment by drnic** [comment]
Want to try replacing in chruby? I'm ok with anything that works :)

## With packer we can investigate creating prebaked images too to speed things up.

Dr Nic Williams
Stark & Wayne LLC - the consultancy for Cloud Foundry
http://starkandwayne.com
+1 415 860 2185
twitter: drnic

**Comment by yudai** [comment]
I don't want to replace the Ruby environment anymore ;-)

I think we have several options to make installing user's gems possible. The list below is what I think of.
Which plan do you think better? Or please add other options.
1. Replacing system-wide RVM with chruby
2. Removing system-wide RVM and Installing apt(system) Ruby and user-local RVM
3. Removing system-wide RVM and Installing apt(system) Ruby and user-local rbenv

**Comment by mdub** [comment]
My PR solves the "can't install gems" problem, but @yudai has a point: compiling Ruby from source all the time is a little wasteful.

Here's another idea:
- install a pre-compiled Ruby 1.9 deb package, using the "filtersquad/chef-brightbox" cookbook.
- set GEM_HOME to "$HOME/.gem/ruby/1.9.3"
- profit!

**Comment by drnic** [comment]
Merged in @mdub's chruby PR.
